services:
  api:
    build: .
    container_name: orginfo_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/orginfo
      BASE_URL: http://localhost:8000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ORGINFO_BASE_SEARCH_URL: https://orginfo.uz/uz/search/organizations/
      CRAWLER_TIMEOUT_SECONDS: 30
      BASIC_AUTH_AUTO_CREATE: "false"
      REDIS_URL: redis://redis:6379/0

  worker:
    build: .
    container_name: orginfo_worker
    entrypoint: []
    command: python -m worker.worker
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/orginfo
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ORGINFO_BASE_SEARCH_URL: https://orginfo.uz/uz/search/organizations/
      CRAWLER_TIMEOUT_SECONDS: 30
      REDIS_URL: redis://redis:6379/0
      WORKER_CONCURRENCY: "4"
      KAFKA_DLQ_TOPIC: "org_jobs_dlq"
      WORKER_MAX_RETRIES: "3"

  db:
    image: postgres:16
    container_name: orginfo_db
    environment:
      POSTGRES_DB: orginfo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7-alpine
    container_name: orginfo_redis
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  zookeeper:
    container_name: orginfo_zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: orginfo_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build: ./frontend
    container_name: orginfo_frontend
    ports:
      - "3000:80"
    depends_on:
      - api
